### ISSUE TITLE
Getting `Query timed out` on AWS EC2 instance

### ISSUE THREAD

**Issue by gauravc-cuelogic** [mafintosh/dns-socket#8]
We are using AWS EC2 instance and have implemented node.js server written in hapi js which is deployed using docker.
On our development server public-ip library is calling dns-socket and is giving proper result.
Now we have setup staging server with similar configuration. Here we are getting below error.

```
error:  Error: Query timed out
    at DNS._ontimeout (/usr/src/app/node_modules/public-ip/node_modules/dns-socket/index.js:98:18)
    at ontimeout (/usr/src/app/node_modules/public-ip/node_modules/dns-socket/index.js:52:10)
    at wrapper (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
```
Can you please suggest some way out of this issue? Let me know if any further information required.

**Comment by silverwind** [comment]
Looks like a network issue, see https://github.com/sindresorhus/public-ip/issues/15#issuecomment-299233250. Closing as there's nothing we can do about that.
